You need to catch NullPointerException and FileNotFoundException, but not catch ArithmeticException or URISyntaxException.
How do you do that?

Requirements:
The main method must call method1.
The main method must catch the NullPointerException exception.
The main method must catch the FileNotFoundException exception.
The main method must not catch the ArithmeticException exception.
The main method must not catch the URISyntaxException exception.
Don't change the method1 method.






package com.codegym.task.task09.task0913;

import java.io.FileNotFoundException;
import java.net.URISyntaxException;

/* 
Exceptions. Just exceptions.

*/

public class Solution {
    public static void main(String[] args) throws ArithmeticException,URISyntaxException {
    
       try{

        method1();
        
       }

        catch(NullPointerException e){
            System.out.println("NullPointerException is caught");
        }
        catch(FileNotFoundException e){
            System.out.println("FileNotFoundException is caught");
        }
      
    }

    public static void method1() throws NullPointerException, ArithmeticException, FileNotFoundException, URISyntaxException {
        
        int i = (int) (Math.random() * 4);
        if (i == 0)
            throw new NullPointerException();
        if (i == 1)
            throw new ArithmeticException();
        if (i == 2)
            throw new FileNotFoundException();
        if (i == 3)
            throw new URISyntaxException("", "");
    }
   
}
